// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv2i-k6hugHdGQf44EgIDQGyhfM4XkDDs',
    appId: '1:741662382903:web:1af00c31e87887ae0658b2',
    messagingSenderId: '741662382903',
    projectId: 'cashbook-4f20d',
    authDomain: 'cashbook-4f20d.firebaseapp.com',
    storageBucket: 'cashbook-4f20d.appspot.com',
    measurementId: 'G-KM43RSXC7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8mQP9rS0WEyKwxo9j-ux7WU8V6OW1Kes',
    appId: '1:741662382903:android:2ec6b95a7b91e8010658b2',
    messagingSenderId: '741662382903',
    projectId: 'cashbook-4f20d',
    storageBucket: 'cashbook-4f20d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxOUFGNej7jHxN_G0Y65WhdvaIc0HE1Vo',
    appId: '1:741662382903:ios:c6eda751cf17aea30658b2',
    messagingSenderId: '741662382903',
    projectId: 'cashbook-4f20d',
    storageBucket: 'cashbook-4f20d.appspot.com',
    iosClientId: '741662382903-2a75cat0v3qmsbne88uhaj8muutqostb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashbookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxOUFGNej7jHxN_G0Y65WhdvaIc0HE1Vo',
    appId: '1:741662382903:ios:c6eda751cf17aea30658b2',
    messagingSenderId: '741662382903',
    projectId: 'cashbook-4f20d',
    storageBucket: 'cashbook-4f20d.appspot.com',
    iosClientId: '741662382903-2a75cat0v3qmsbne88uhaj8muutqostb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashbookApp',
  );
}
